// node scripts/build-phrases.cjs path/to/BPMFMappings.txt path/to/phrase.occ
const { readFileSync, writeFileSync } = require("node:fs");
const { resolve } = require("node:path");
const { createHash } = require("node:crypto");
const vm = require("node:vm");

function readPinned(file, hash) {
  const data = readFileSync(file);
  if (createHash("sha256").update(data).digest("hex") !== hash) {
    throw new Error(`Unexpected source: ${file}. Review provenance before updating hashes.`);
  }
  return data.toString("utf8");
}
const mappings = readPinned(process.argv[2], "baa9452ef927b3268f600ca69fe27eb0838b8be31c8ae0dd8540561db68c7ffd");
const occurrences = readPinned(process.argv[3], "2dbe37c1c61266f65d158a3e0020a0c1f2a75039ebd7f1580ef8e537a7bc8779");
const context = vm.createContext({});
vm.runInContext(readFileSync(resolve(__dirname, "../src/core/dictionary.js"), "utf8"), context);
const dictionary = context.ZHUYIN_DICTIONARY;
const counts = new Map();
for (const line of occurrences.split(/\r?\n/)) {
  const [word, count] = line.trim().split(/\s+/);
  if (word && /^\p{Script=Han}+$/u.test(word) && Number.isSafeInteger(Number(count)) && Number(count) > 0) {
    counts.set(word, Number(count));
  }
}
const characters = Object.create(null);
for (const chars of Object.values(dictionary)) {
  for (const char of chars) characters[char] = counts.get(char) ?? 0;
}
const phrases = new Map();
for (const line of mappings.split(/\r?\n/)) {
  const [word, ...readings] = line.trim().split(/\s+/);
  const chars = [...word];
  const count = counts.get(word);
  if (!count || chars.length < 2 || chars.length > 6 || chars.length !== readings.length) continue;
  // Every phrase must remain selectable using our existing character dictionary.
  if (!chars.every((char, index) => dictionary[readings[index]]?.includes(char))) continue;
  const key = readings.join("-");
  if (!phrases.has(key)) phrases.set(key, new Map());
  phrases.get(key).set(word, count);
}
const lexicalCounts = new Map(Object.entries(characters));
const entries = [...phrases].sort(([a], [b]) => a < b ? -1 : 1).map(([key, words]) => {
  for (const [word, count] of words) lexicalCounts.set(word, count);
  const ordered = [...words].sort(([a, ac], [b, bc]) => bc - ac || (a < b ? -1 : a > b ? 1 : 0));
  return `  ${JSON.stringify(key)}: ${JSON.stringify(ordered)}`;
});
// Add-one smoothing denominator, shared by character and phrase edges.
const total = [...lexicalCounts.values()].reduce((sum, count) => sum + count + 1, 0);
const charEntries = Object.entries(characters).sort(([a], [b]) => a < b ? -1 : 1);
const result = `// Generated by scripts/build-phrases.cjs; do not edit by hand.\n` +
  `// McBopomofo f5ba010ce8795d283ee336ca7d16380f200bd2ec.\n` +
  `// Copyright (c) 2011-2026 Mengjuei Hsieh et al., MIT; libtabe notices also apply.\n` +
  `// Full notices and provenance: third_party/mcbopomofo/.\n` +
  `globalThis.ZHUYIN_PHRASES = Object.freeze({\n${entries.join(",\n")}\n});\n` +
  `globalThis.ZHUYIN_CHARACTER_COUNTS = Object.freeze(${JSON.stringify(Object.fromEntries(charEntries))});\n` +
  `globalThis.ZHUYIN_FREQUENCY_TOTAL = ${total};\n`;
writeFileSync(resolve(__dirname, "../src/core/phrases.js"), result);
console.log(`${phrases.size} reading sequences, ${[...phrases.values()].reduce((sum, words) => sum + words.size, 0)} phrase entries, ${Buffer.byteLength(result)} bytes`);
