const { readFileSync, writeFileSync } = require("node:fs");
const { resolve } = require("node:path");
const vm = require("node:vm");

const MIN_COUNT = 5;

function buildContext() {
  const root = resolve(__dirname, "..");
  const context = vm.createContext({});
  vm.runInContext(readFileSync(resolve(root, "src/core/phrases.js"), "utf8"), context);
  const counts = new Map();
  const seenWords = new Set();
  for (const entries of Object.values(context.ZHUYIN_PHRASES)) {
    for (const [word, count] of entries) {
      if (seenWords.has(word)) continue;
      seenWords.add(word);
      const chars = [...word];
      for (let index = 1; index < chars.length; index++) {
        const pair = chars[index - 1] + chars[index];
        counts.set(pair, (counts.get(pair) ?? 0) + count);
      }
    }
  }
  const retained = [...counts]
    .filter(([, count]) => count >= MIN_COUNT)
    .sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0);
  const result = `// Generated by scripts/build-context.cjs; do not edit by hand.\n` +
    `// Adjacent Han counts derived from the bundled McBopomofo/libtabe phrase data.\n` +
    `// Pairs with corpus count below ${MIN_COUNT} are omitted as weak context evidence.\n` +
    `// Full notices and provenance: third_party/mcbopomofo/.\n` +
    `globalThis.ZHUYIN_CONTEXT_COUNTS = Object.freeze(${JSON.stringify(Object.fromEntries(retained))});\n`;
  writeFileSync(resolve(root, "src/core/context.js"), result);
  console.log(`${retained.length} context pairs, ${Buffer.byteLength(result)} bytes`);
}

if (require.main === module) buildContext();

module.exports = { buildContext };
